[package]
name = "wonderful_edge_cases"
version = "0.1.0"
authors = ["pinkforest <36498018+pinkforest@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
state = "0.4.2"
